name: CI
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check tags
        id: check_tags
        run: |
          echo ::group::Deno cache
          deno run -A --no-lock .github/scripts/check_tag.ts
      - name: Publish
        if: ${{steps.check_tags.outputs.NEW_TAG}}
        run: |
          echo ::group::Deno cache
          deno run -A --no-lock .github/scripts/publish.ts
        env:
          NEW_TAG: ${{steps.check_tags.outputs.NEW_TAG}}
          GITHUB_TOKEN: ${{secrets.CI_GITHUB_TOKEN}}
